[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags = 
    -I ../common
lib_deps = 
    bblanchon/ArduinoJson @ ^6.21.3
    madhephaestus/ESP32Servo @ ^1.1.1
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
